// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for NotificationAcceptedStatus.
const (
	Pending NotificationAcceptedStatus = "pending"
)

// Valid indicates whether the value is a known member of the NotificationAcceptedStatus enum.
func (e NotificationAcceptedStatus) Valid() bool {
	switch e {
	case Pending:
		return true
	default:
		return false
	}
}

// Defines values for NotificationPriority.
const (
	Bulk          NotificationPriority = "bulk"
	Transactional NotificationPriority = "transactional"
)

// Valid indicates whether the value is a known member of the NotificationPriority enum.
func (e NotificationPriority) Valid() bool {
	switch e {
	case Bulk:
		return true
	case Transactional:
		return true
	default:
		return false
	}
}

// Defines values for NotificationType.
const (
	Email NotificationType = "email"
	Push  NotificationType = "push"
	Sms   NotificationType = "sms"
)

// Valid indicates whether the value is a known member of the NotificationType enum.
func (e NotificationType) Valid() bool {
	switch e {
	case Email:
		return true
	case Push:
		return true
	case Sms:
		return true
	default:
		return false
	}
}

// BatchItemResult Exactly one of `notification` or `error` is set.
type BatchItemResult struct {
	Error *ErrorResponse `json:"error,omitempty"`

	// Index Position of the item in the request array.
	Index        int                   `json:"index"`
	Notification *NotificationAccepted `json:"notification,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Machine-readable error class: `validation_error`,
	// `template_not_found`, `bad_request`, `not_found`,
	// `internal_error`.
	Code string `json:"code"`

	// Field The invalid input field, for validation errors.
	Field   *string `json:"field,omitempty"`
	Message string  `json:"message"`
}

// NotificationAccepted defines model for NotificationAccepted.
type NotificationAccepted struct {
	CreatedAt time.Time `json:"created_at"`

	// Id Notification identifier for tracking.
	Id string `json:"id"`

	// Status Always `pending` — delivery is asynchronous.
	Status NotificationAcceptedStatus `json:"status"`
}

// NotificationAcceptedStatus Always `pending` — delivery is asynchronous.
type NotificationAcceptedStatus string

// NotificationPriority Queue lane selection. Defaults to `transactional`. Bulk senders
// (campaigns) must set `bulk` so they never delay transactional
// notifications such as OTPs or password resets.
type NotificationPriority string

// NotificationType Notification delivery channel.
type NotificationType string

// Recipient Delivery address. Exactly the field matching the notification
// type must be set: `email` for email, `phone_number` for sms,
// `device_token` for push.
type Recipient struct {
	// DeviceToken FCM/APNs device token for push notifications.
	DeviceToken *string `json:"device_token,omitempty"`

	// Email Email address (RFC 5322) for email notifications.
	Email *string `json:"email,omitempty"`

	// PhoneNumber Phone number (E.164) for SMS notifications.
	PhoneNumber *string `json:"phone_number,omitempty"`

	// UserId Optional reference to the receiving user.
	UserId *string `json:"user_id,omitempty"`
}

// SendNotificationBatchRequest defines model for SendNotificationBatchRequest.
type SendNotificationBatchRequest struct {
	Notifications []SendNotificationRequest `json:"notifications"`
}

// SendNotificationBatchResponse defines model for SendNotificationBatchResponse.
type SendNotificationBatchResponse struct {
	Results []BatchItemResult `json:"results"`
}

// SendNotificationRequest defines model for SendNotificationRequest.
type SendNotificationRequest struct {
	// Metadata Opaque key-value pairs carried with the notification.
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Priority Queue lane selection. Defaults to `transactional`. Bulk senders
	// (campaigns) must set `bulk` so they never delay transactional
	// notifications such as OTPs or password resets.
	Priority *NotificationPriority `json:"priority,omitempty"`

	// Recipient Delivery address. Exactly the field matching the notification
	// type must be set: `email` for email, `phone_number` for sms,
	// `device_token` for push.
	Recipient Recipient `json:"recipient"`

	// TemplateData Values substituted into the template.
	TemplateData *map[string]interface{} `json:"template_data,omitempty"`

	// TemplateId Template to render at delivery time. Omit to use the default
	// template for the notification type.
	TemplateId *string `json:"template_id,omitempty"`

	// Type Notification delivery channel.
	Type NotificationType `json:"type"`
}

// Template defines model for Template.
type Template struct {
	// Body Go template for the body.
	Body      string `json:"body"`
	Id        string `json:"id"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`

	// Subject Go template for the email subject or push title.
	Subject string `json:"subject"`

	// Type Notification delivery channel.
	Type NotificationType `json:"type"`
}

// TemplateList defines model for TemplateList.
type TemplateList struct {
	Templates []TemplateSummary `json:"templates"`
}

// TemplateSummary defines model for TemplateSummary.
type TemplateSummary struct {
	Id string `json:"id"`

	// IsDefault Whether this is the default template for its type.
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`

	// Type Notification delivery channel.
	Type NotificationType `json:"type"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// ListTemplatesParams defines parameters for ListTemplates.
type ListTemplatesParams struct {
	// Type Only return templates for this notification type.
	Type *NotificationType `form:"type,omitempty" json:"type,omitempty"`
}

// SendNotificationJSONRequestBody defines body for SendNotification for application/json ContentType.
type SendNotificationJSONRequestBody = SendNotificationRequest

// SendNotificationBatchJSONRequestBody defines body for SendNotificationBatch for application/json ContentType.
type SendNotificationBatchJSONRequestBody = SendNotificationBatchRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a notification
	// (POST /notifications)
	SendNotification(ctx echo.Context) error
	// Send multiple notifications
	// (POST /notifications/batch)
	SendNotificationBatch(ctx echo.Context) error
	// List available templates
	// (GET /templates)
	ListTemplates(ctx echo.Context, params ListTemplatesParams) error
	// Get template details
	// (GET /templates/{type}/{id})
	GetTemplate(ctx echo.Context, pType NotificationType, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SendNotification converts echo context to params.
func (w *ServerInterfaceWrapper) SendNotification(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendNotification(ctx)
	return err
}

// SendNotificationBatch converts echo context to params.
func (w *ServerInterfaceWrapper) SendNotificationBatch(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SendNotificationBatch(ctx)
	return err
}

// ListTemplates converts echo context to params.
func (w *ServerInterfaceWrapper) ListTemplates(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTemplatesParams
	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", ctx.QueryParams(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTemplates(ctx, params)
	return err
}

// GetTemplate converts echo context to params.
func (w *ServerInterfaceWrapper) GetTemplate(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "type" -------------
	var pType NotificationType

	err = runtime.BindStyledParameterWithOptions("simple", "type", ctx.Param("type"), &pType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter type: %s", err))
	}

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTemplate(ctx, pType, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/notifications", wrapper.SendNotification, options.OperationMiddlewares["sendNotification"]...)
	router.POST(options.BaseURL+"/notifications/batch", wrapper.SendNotificationBatch, options.OperationMiddlewares["sendNotificationBatch"]...)
	router.GET(options.BaseURL+"/templates", wrapper.ListTemplates, options.OperationMiddlewares["listTemplates"]...)
	router.GET(options.BaseURL+"/templates/:type/:id", wrapper.GetTemplate, options.OperationMiddlewares["getTemplate"]...)

}

type BadRequestJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type SendNotificationRequestObject struct {
	Body *SendNotificationJSONRequestBody
}

type SendNotificationResponseObject interface {
	VisitSendNotificationResponse(w http.ResponseWriter) error
}

type SendNotification202JSONResponse NotificationAccepted

func (response SendNotification202JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotification400JSONResponse struct{ BadRequestJSONResponse }

func (response SendNotification400JSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response SendNotificationdefaultJSONResponse) VisitSendNotificationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationBatchRequestObject struct {
	Body *SendNotificationBatchJSONRequestBody
}

type SendNotificationBatchResponseObject interface {
	VisitSendNotificationBatchResponse(w http.ResponseWriter) error
}

type SendNotificationBatch202JSONResponse SendNotificationBatchResponse

func (response SendNotificationBatch202JSONResponse) VisitSendNotificationBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationBatch400JSONResponse struct{ BadRequestJSONResponse }

func (response SendNotificationBatch400JSONResponse) VisitSendNotificationBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SendNotificationBatchdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response SendNotificationBatchdefaultJSONResponse) VisitSendNotificationBatchResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesRequestObject struct {
	Params ListTemplatesParams
}

type ListTemplatesResponseObject interface {
	VisitListTemplatesResponse(w http.ResponseWriter) error
}

type ListTemplates200JSONResponse TemplateList

func (response ListTemplates200JSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTemplatesdefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response ListTemplatesdefaultJSONResponse) VisitListTemplatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplateRequestObject struct {
	Type NotificationType `json:"type"`
	Id   string           `json:"id"`
}

type GetTemplateResponseObject interface {
	VisitGetTemplateResponse(w http.ResponseWriter) error
}

type GetTemplate200JSONResponse Template

func (response GetTemplate200JSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplate404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTemplate404JSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTemplatedefaultJSONResponse struct {
	Body       ErrorResponse
	StatusCode int
}

func (response GetTemplatedefaultJSONResponse) VisitGetTemplateResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Send a notification
	// (POST /notifications)
	SendNotification(ctx context.Context, request SendNotificationRequestObject) (SendNotificationResponseObject, error)
	// Send multiple notifications
	// (POST /notifications/batch)
	SendNotificationBatch(ctx context.Context, request SendNotificationBatchRequestObject) (SendNotificationBatchResponseObject, error)
	// List available templates
	// (GET /templates)
	ListTemplates(ctx context.Context, request ListTemplatesRequestObject) (ListTemplatesResponseObject, error)
	// Get template details
	// (GET /templates/{type}/{id})
	GetTemplate(ctx context.Context, request GetTemplateRequestObject) (GetTemplateResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// SendNotification operation middleware
func (sh *strictHandler) SendNotification(ctx echo.Context) error {
	var request SendNotificationRequestObject

	var body SendNotificationJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendNotification(ctx.Request().Context(), request.(SendNotificationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendNotification")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendNotificationResponseObject); ok {
		return validResponse.VisitSendNotificationResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SendNotificationBatch operation middleware
func (sh *strictHandler) SendNotificationBatch(ctx echo.Context) error {
	var request SendNotificationBatchRequestObject

	var body SendNotificationBatchJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SendNotificationBatch(ctx.Request().Context(), request.(SendNotificationBatchRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendNotificationBatch")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendNotificationBatchResponseObject); ok {
		return validResponse.VisitSendNotificationBatchResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListTemplates operation middleware
func (sh *strictHandler) ListTemplates(ctx echo.Context, params ListTemplatesParams) error {
	var request ListTemplatesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTemplates(ctx.Request().Context(), request.(ListTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListTemplatesResponseObject); ok {
		return validResponse.VisitListTemplatesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTemplate operation middleware
func (sh *strictHandler) GetTemplate(ctx echo.Context, pType NotificationType, id string) error {
	var request GetTemplateRequestObject

	request.Type = pType
	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplate(ctx.Request().Context(), request.(GetTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTemplateResponseObject); ok {
		return validResponse.VisitGetTemplateResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"xFndctu4FX6VM2wvkqlCyY43u9Xe1Nn8jGeaxLXd7sUqY0LEkYU1CTA4oG2NRzN9iD5hn6RzAJIiRUr2",
	"Tr3eO4oAz893vvMD6D5KTV4YjdpRNL2PLFJhNKH/8VbIM/xWIjn+lRrtUPtHURSZSoVTRo9/JaP5HaVL",
	"zAU//dniIppGfxpvRI/DKo3fW2vsWaUkWq/Xo0gipVYVLCyaRhdLBBuUgiJQ+kZkSsbRehSdaIdWi8zL",
	"eD6L/qnxrsDUoQRCe4MWkD/xJn027oMptfxD8EEJFsmUNkWQBgm0cYB3ilwc8YeVzBBJly5PHOZnSGXm",
	"beyKfX8nUpetwGgEs4BEG6cWlQsJGAuJdzrhmBC6OBpFhTUFWqcCV7AOym/wbhQpLfGub82pIcWPbIpb",
	"IiiHOSjtn2tyCGvFiu1wqwKjaaS0wyu0LLVt/EMmfW7tPU5TLBxKjx7rURZlNP2lMvNro8vMf8XUsaqu",
	"R9P7LVRSI7Hv3ieRLpXGVxaFFPMMA6EgzQTRFBLPeG/QZQB9NNOJw7zIhMNLbdzlgjmXjCCZC3lZAcI/",
	"W2sznagqXyop8Uxv0CJnlb5iDxYKM9m3kXlWJR8oXZQO/MYRLIyFjYXBdOI44J3Ii4yFW0xVoVC7GHOh",
	"siGtORKJK4/N1toW9B7Bzf6hGAyGsB8Ki8KhvBSe/Qtjc36KpHD4yqkch6xUA8C0tYGSqPknWo+LsyK9",
	"VvoqHhJGTriS+gKPs1uxIkgK1FLpqwT+++//gMRM3aBdcb4JWul0aY02ZQBalzlDU33QwmQHhkpGjfpR",
	"G4iH0Dy1yljlVsHohfClI3JWaBIpbxAc3K47/yixRMiERiDM0G+L4V34msAZSDoCkhjeltk1EGqJlmb6",
	"RSryQqgrTS8hL8lxvYFkXmbXCZDhGrACjVyHJWZiBR1pM91OfgIq0yUIgi8Xp8RlrBBEt8b6yomOQk7U",
	"gG47xjoH0O1idOEX97KkCWa6FFpj1g5inSGUc2yKkpaDGs/qlOqreldLF1JaJIqhLuZcLn3WQs71X+kr",
	"/6qN0EyzqoDznCPmppB4mxLPaP84gqRYGo2XusznaMMK5cRFRuKNSvHSmWvUYYF9CLh2E7C9s+/Fh58+",
	"jY9PPxOEbeC3NfI6NtNgegUg+42NX9fQwIuzDz/Bd68PD19uvOvL3lQyobWIr82tyOha/K16H6cmH7Kg",
	"jdFAT+NVCKvw4n188OYoGHH+6XyfCX85+uHN5ODw9dF3b74f0loS2suhQvWlCEQGiwu0qD2oVQtNUd0w",
	"Hfjjrjov7vsf/hoNFZVesThHLdtU93NGa2bsMqDjJb/gvk4PdehtHbV47iLi7iSIOJhMRlGudP2zsdWP",
	"Cb2K2LXk6+M929XorZ+rHu/U9kC2fsDgWv5jTN2Jf45OSOH8ECqkVIEfp509PX5tk0p8KxGucfXqRmQl",
	"QiGUJUiFtQol3Cq37NWYVrpujC5areWx81nTjjw4rYK4T8CmcjLG9RS1HwZnS9z2/F/sLjeUOTnlSp6+",
	"la4SqhY76GmjcyhJL6pFTk3rOyAIt2kYPJjE8CVXjjeUhF5d1YpnuhYdho8t2IEtqRpck963mKVmeNhx",
	"VSN7bDR849vmqRfSjs4QYWun+wydG7nqg/TRQM9T3hnvntn6r+mymWCa5bkxGQrtzwwix8EPqQx2P8qq",
	"0FCqT6BuXk65DOPfDXM/3lXAezc63m48GAV490Xk72qobtRuPr681fLOyzwXdvVgedto2GddLa1nYIj5",
	"o1je5UE3oj8v0S2RI6mIB+9WrnVDrXiQ5ezaaBig0saen4M98H7XcegZeNAHdu0P4AszcCTxpyjqlpPq",
	"nEnwohoKzz+djzzBX4LQEr7x4O9ByxmkmW6fW5qSFkPdRCl0i3AuaR1/chT+pN8d5eFWEIjqdDfyVx2V",
	"SJQ/bgrmUhQFagKl4dbYa7TViO9TcGsuJzg+PYlG0Q1aCn5P4oN4wvEwBWpRqGgavY4n8WueZYVbeq6N",
	"e1NMYULSMCP92xMZTXtdOQrBQnJvqyL3JBdGO6ejLju4o/kXreu9w8nhk5mx4xqlNz90zkV1OH1ODbOF",
	"g3E0mexS3/gzbt1VeqVNiu//rHun6G/N6iLjIwiikwR+R5cB4zmPcm0edD32EykIi1BYkyKRHxwkMt9R",
	"u2w1rWbyYBJYLIx1BALCzDfTBVp/Azbi468Arw9SoaEQ1imRZSs+5qaIMnB9Pw/95PlMZOwcB56ZkfsH",
	"+AFq+g2bIP0IhAgF2lf+9rEawP94QuZl5lSRdWc9CsTsNOorHKhK3OAvml1c1qzI0aGlaPpL7wSpsxVY",
	"dKXVTf+jatZRNDBscsfhD7+VaFd1F5rWPem3V5KqzX3t0WTyZDTpTD4DrDi+ESrzl7QNAvGTBZSVguhr",
	"2Irm+J4RXI/vlVy3IrvjJHHyLpQbSk2BEuarfqCmMKsdmEXhLwOa6U5VCvcjnVurgeLyERs29cnkqcB9",
	"s8eEbhX4P5gxGtTiB6HdOrbvNZ6DXoN/5dQRk+iEyuracvQwp5q/nZ6KiB+xNeFW5gSTw19eIaClzaJp",
	"NBaFGt8cROuv6/8FAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
